### ISSUE TITLE
glia convert broadcast input array shape error

### ISSUE THREAD

**Issue by KRolnick89** [tbenst/glia#10]
Tyler, the glia convert function has given me this error on a couple of runs. I've tried changing the analog calibration, it appears there are zero missing start times/stimuli, however. 

(glia) vangelderlab@vangelderlab-Ubuntu:~/Desktop/171029$ glia analyze R1_E3 convert
Analyzing R1_E3_AMES_470min_checkerboard_durations
Saving checkerboard NPZ file.
Creating experiments
100%|█████████████████████████████████████| 4006/4006 [00:03<00:00, 1134.11it/s]
Conditions: R1_E3_AMES_470min_checkerboard_durations [1.0]
converting to ndarray
100%|██████████████████████████████████████████| 59/59 [00:00<00:00, 774.16it/s]
Traceback (most recent call last):
  File "/home/vangelderlab/anaconda3/envs/glia/bin/glia", line 11, in <module>
    load_entry_point('glia', 'console_scripts', 'glia')()
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1092, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vangelderlab/Desktop/glia-master/glia_scripts/command_line.py", line 53, in new_func
    *args[2:], **kwargs)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vangelderlab/Desktop/glia-master/glia_scripts/command_line.py", line 485, in convert_cmd
    lambda x: x["lifespan"])
  File "/home/vangelderlab/Desktop/glia-master/glia_scripts/convert.py", line 380, in save_checkerboard_npz
    training_data[condition_index, size_index] = pad_td
ValueError: could not broadcast input array from shape (59,1000,8,8,10) into shape (60,1000,8,8,10)

**Comment by tbenst** [comment]
Could you try deleting the .stim file and show the output when you try
again? The calibration won't be used if the .stim file already exists

**Comment by KRolnick89** [comment]
The output after deleting the stim file is below. I did try multiple calibration adjustments (-c config) but continue to receive missing start times error despite 0/4006 missing. I am able to get an integrity plot using --ignore-extra.

(glia) vangelderlab@vangelderlab-Ubuntu:~/Desktop/171029$ glia analyze R1_E3 integrity
Analyzing R1_E3_AMES_470min_checkerboard_durations
No .stim file found. Creating from .analog file.
analog autocalibration of [  1846.   5386.   6093.   9128.   9532.  12870.]
getting start times
0/4006 start times were missing. Estimating missing times
validating stimulus list
{'lifespan': 0.5, 'backgroundColor': 'white', 'metadata': {'group': '88e69258-f6a8-46b3-a89d-d57a6c308e1d', 'cohort': 'bc81807e-9bb5-4173-8424-a9a10a029118', 'block': True, 'class': 'B', 'target': 'DIFFERENT'}, 'age': 0, 'stimulusType': 'CHECKERBOARD', 'color': 'black', 'alternateColor': 'white', 'size': 63, 'angle': 0.7853981633974483, 'count': 0, 'stimulusIndex': 4007} previous start time: 3151.84092
Traceback (most recent call last):
  File "/home/vangelderlab/Desktop/glia-master/glia_scripts/command_line.py", line 299, in analyze
    metadata, stimulus_list, method = glia.read_stimulus(stimulus_file)
  File "/home/vangelderlab/Desktop/glia-master/glia/eyecandy.py", line 152, in read_stimulus
    with open(file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'R1_E3_AMES_470min_checkerboard_durations.stim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vangelderlab/anaconda3/envs/glia/bin/glia", line 11, in <module>
    load_entry_point('glia', 'console_scripts', 'glia')()
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1075, in invoke
    Command.invoke(self, ctx)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/vangelderlab/anaconda3/envs/glia/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/vangelderlab/Desktop/glia-master/glia_scripts/command_line.py", line 308, in analyze
    config.analog_calibration, threshold)
  File "/home/vangelderlab/Desktop/glia-master/glia/eyecandy.py", line 246, in create_stimuli
    validate_stimulus_list(stimulus_list,stimulus_gen,ignore_extra, within_threshold)
  File "/home/vangelderlab/Desktop/glia-master/glia/eyecandy.py", line 486, in validate_stimulus_list
    raise ValueError("More stimuli than start times detected." \
ValueError: More stimuli than start times detected.Use --ignore-extra to ignore.
