### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by babinod** [tbenst/glia#24]
(glia) darwin@Sauron:~/Desktop/Link to mea/data/200320/analysis$ glia analyze R1_E5 integrity
version 0.5.1
Analyzing R1_E5_AMES_290min_grating_contrast
Traceback (most recent call last):
  File "/home/darwin/anaconda3/envs/glia/bin/glia", line 11, in <module>
    load_entry_point('glia', 'console_scripts', 'glia')()
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1146, in invoke
    Command.invoke(self, ctx)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/darwin/glia/glia_scripts/command_line.py", line 301, in analyze
    experiment_protocol = glia.get_experiment_protocol(lab_notebook, name)
  File "/home/darwin/glia/glia/eyecandy.py", line 103, in get_experiment_protocol
    logger.info(f"inside get_experiment_protocol: {experiment['filename']},"
TypeError: 'NoneType' object is not subscriptable

**Comment by tbenst** [comment]
@babinod could not replicate so closing for now, but let me know if still an issue?

```
(glia) darwin@Sauron:/mea/MCS/200320/analysis$ glia analyze R1_E5 integrity
version 0.5.1
Analyzing R1_E5_AMES_290min_grating_contrast
Traceback (most recent call last):
  File "/home/darwin/glia/glia_scripts/command_line.py", line 333, in analyze
    frame_log = pd.read_csv(frames_file)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'2020-03-21T01_39_50.860Z_eyecandy_frames.frames' does not exist: b'2020-03-21T01_39_50.860Z_eyecandy_frames.frames'
[Errno 2] File b'2020-03-21T01_39_50.860Z_eyecandy_frames.frames' does not exist: b'2020-03-21T01_39_50.860Z_eyecandy_frames.frames'
Attempting to continue...
Creating integrity chart
Applying pipeline
100%|████████████████████████████████████████████████████████████████████████████████████████| 357/357 [02:40<00:00,  1.53it/s]
Applying pipeline
100%|████████████████████████████████████████████████████████████████████████████████████████| 357/357 [00:07<00:00, 50.54it/s]
Applying pipeline
Finished
```
