### ISSUE TITLE
--by-channel broken, TypeError: must be str, not int

### ISSUE THREAD

**Issue by babinod** [tbenst/glia#25]
(glia) darwin@Sauron:~/Desktop/Link to mea/MCS/200410_DENAQ/analysis$ glia analyze --by-channel R2_E1_DENAQ_320min_grating_speeds.txt integrity
version 0.5.1
Analyzing R2_E1_DENAQ_320min_grating_speeds
Traceback (most recent call last):
  File "/home/darwin/glia/glia_scripts/command_line.py", line 333, in analyze
    frame_log = pd.read_csv(frames_file)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'2020-04-10T21_55_00.969Z_eyecandy_frames.frames' does not exist: b'2020-04-10T21_55_00.969Z_eyecandy_frames.frames'
[Errno 2] File b'2020-04-10T21_55_00.969Z_eyecandy_frames.frames' does not exist: b'2020-04-10T21_55_00.969Z_eyecandy_frames.frames'
Attempting to continue...
Traceback (most recent call last):
  File "/home/darwin/anaconda3/envs/glia/bin/glia", line 11, in <module>
    load_entry_point('glia', 'console_scripts', 'glia')()
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1146, in invoke
    Command.invoke(self, ctx)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/darwin/glia/glia_scripts/command_line.py", line 373, in analyze
    ctx.obj["units"] = glia.combine_units_by_channel(ctx.obj["units"])
  File "/home/darwin/glia/glia/files.py", line 187, in combine_units_by_channel
    new_units[channel] = merge_units(new_units[channel], unit)
  File "/home/darwin/glia/glia/files.py", line 198, in merge_units
    new = Unit(retina_id, channel, "all", spike_train)
  File "/home/darwin/glia/glia/types.py", line 69, in __init__
    Unit.nunit = max(unit_num+1, Unit.nunit)
TypeError: must be str, not int

**Comment by tbenst** [comment]
Thank Darwin, tasing a look tomorrow!

**Comment by tbenst** [comment]
@babinod fixed, and ran that command on sauron so the plots are ready
