### ISSUE TITLE
Update seems to have caused issue

### ISSUE THREAD

**Issue by babinod** [tbenst/glia#26]
(glia) darwin@Sauron:~/Desktop/Link to mea/MCS/200428_BENAQ/analysis$ glia classify R1_E2
Traceback (most recent call last):
  File "/home/darwin/anaconda3/envs/glia/bin/glia", line 11, in <module>
    load_entry_point('glia', 'console_scripts', 'glia')()
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/darwin/anaconda3/envs/glia/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/darwin/glia/glia_scripts/command_line.py", line 806, in classify_cmd
    nsamples, n_draws, px_per_deg=px_per_deg)
TypeError: grating_svc() got an unexpected keyword argument 'px_per_deg'

**Comment by tbenst** [comment]
@babinod thanks, fixed in https://github.com/tbenst/glia/commit/006a7427b20ee87eff32fce9bbf67de7e19a6d92. Need to get automated testing working again to prevent this, too much coverage on CLI for breaking things in dumb ways. Thx for your patience!

**Comment by babinod** [comment]
Thank you! This one also needs addition of px_per_deg for "letters', got it to work on my local file.
